backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "gem"
    label: "Gem"
    folder: "content/gem"
    create: true
    fields:
      - { label: "Main Heading", name: "mainHeading", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Heading 1", name: "headingOne", widget: "string" }
      - { label: "Heading 2", name: "headingTwo", widget: "string" }
      - { label: "Description 1", name: "desc1", widget: "markdown" }
      - { label: "Description 2", name: "desc2", widget: "markdown" }
      - { label: "Details", name: "details", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Main Image", name: "imageMain", widget: "image" }
      - { label: "Columns", name: "cols", widget: "number" }
      - { label: "Rows", name: "rows", widget: "number" }
